// Code generated by "json-ice --type=Issue24Struct"; DO NOT EDIT.

package tests

import "github.com/moznion/go-json-ice/serializer"

func MarshalIssue24StructAsJSON(s *Issue24Struct) ([]byte, error) {
	buff := make([]byte, 1, 28)
	buff[0] = '{'
	buff = append(buff, "\"foo\":"...)
	buff = serializer.AppendSerializedString(buff, s.Foo)
	buff = append(buff, ',')
	if buff[len(buff)-1] == ',' {
		buff[len(buff)-1] = '}'
	} else {
		buff = append(buff, '}')
	}
	return buff, nil
}
