// Code generated by "json-ice --type=OmitemptyStruct"; DO NOT EDIT.

package tests

import (
	"bytes"

	"github.com/moznion/go-json-ice/serializer"
)

func (s *OmitemptyStruct) MarshalJSON() ([]byte, error) {
	var err error
	initBytes := make([]byte, 1, 500)
	initBytes[0] = '{'
	buff := bytes.NewBuffer(initBytes)
	if s.EmptyBool != false {
		_, err = buff.WriteString("\"empty_bool\":")
		if err != nil {
			return nil, err
		}
		_, err = buff.Write(serializer.SerializeBool(s.EmptyBool))
		if err != nil {
			return nil, err
		}
		_, err = buff.WriteRune(',')
		if err != nil {
			return nil, err
		}
	}
	if s.EmptyInt != 0 {
		_, err = buff.WriteString("\"empty_int\":")
		if err != nil {
			return nil, err
		}
		_, err = buff.Write(serializer.SerializeInt(int64(s.EmptyInt)))
		if err != nil {
			return nil, err
		}
		_, err = buff.WriteRune(',')
		if err != nil {
			return nil, err
		}
	}
	if s.EmptyUint != 0 {
		_, err = buff.WriteString("\"empty_uint\":")
		if err != nil {
			return nil, err
		}
		_, err = buff.Write(serializer.SerializeUint(uint64(s.EmptyUint)))
		if err != nil {
			return nil, err
		}
		_, err = buff.WriteRune(',')
		if err != nil {
			return nil, err
		}
	}
	if s.EmptyFloat != 0 {
		_, err = buff.WriteString("\"empty_float\":")
		if err != nil {
			return nil, err
		}
		_, err = buff.Write(serializer.SerializeFloat(float64(s.EmptyFloat)))
		if err != nil {
			return nil, err
		}
		_, err = buff.WriteRune(',')
		if err != nil {
			return nil, err
		}
	}
	if s.EmptyString != "" {
		_, err = buff.WriteString("\"empty_string\":")
		if err != nil {
			return nil, err
		}
		_, err = buff.Write(serializer.SerializeString(s.EmptyString))
		if err != nil {
			return nil, err
		}
		_, err = buff.WriteRune(',')
		if err != nil {
			return nil, err
		}
	}
	_, err = buff.WriteString("\"not_empty_string\":")
	if err != nil {
		return nil, err
	}
	_, err = buff.Write(serializer.SerializeString(s.NotEmptyString))
	if err != nil {
		return nil, err
	}
	_, err = buff.WriteRune(',')
	if err != nil {
		return nil, err
	}
	bs := buff.Bytes()
	if bs[len(bs)-1] == ',' {
		bs[len(bs)-1] = '}'
	} else {
		bs = append(bs, '}')
	}
	return bs, nil
}
