// Code generated by "json-ice --type=version --cap-size=74"; DO NOT EDIT.

package internal

import "github.com/moznion/go-json-ice/serializer"

func MarshalVersionAsJSON(s *version) ([]byte, error) {
	buff := make([]byte, 1, 74)
	buff[0] = '{'
	buff = append(buff, "\"version\":"...)
	buff = serializer.AppendSerializedString(buff, s.Version)
	buff = append(buff, ',')
	buff = append(buff, "\"revision\":"...)
	buff = serializer.AppendSerializedString(buff, s.Revision)
	buff = append(buff, ',')
	if buff[len(buff)-1] == ',' {
		buff[len(buff)-1] = '}'
	} else {
		buff = append(buff, '}')
	}
	return buff, nil
}
