name: Go
on: [push]
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get go toolchains
      run: |
        go get -u golang.org/x/tools/cmd/goimports
        go get -u golang.org/x/lint/golint
        sudo cp $GOPATH/bin/goimports /usr/bin/
        sudo cp $GOPATH/bin/golint /usr/bin/
      env:
        GOPATH: /home/runner/work/go-json-ice/go

    - name: Get tinygo runtime
      run: |
        wget -P /tmp/ https://github.com/tinygo-org/tinygo/releases/download/v0.13.1/tinygo_0.13.1_amd64.deb
        sudo dpkg -i /tmp/tinygo_0.13.1_amd64.deb

    - name: Do test
      run: make test
      env:
        GOPATH: /home/runner/work/go-json-ice/go

    - name: Compile tinygo wasm; to check success or not
      run: /usr/local/tinygo/bin/tinygo build -o main.wasm -target wasm ./tests/tinygo/main.go
      env:
        GOPATH: /home/runner/work/go-json-ice/go

